Added python34 setup tools and easy_install pip to python34 role
cfpb/aurora pull request #208
Opened 2017-04-25 13:12 UTC by rioh

2017-04-25 21:56 UTC, tanderegg requested changes

2017-04-25 21:56 UTC, tanderegg commented on deploy/roles/python3/tasks/main.yml
>      disable_gpg_check: yes
@rioh You can actually remove this disable_gpg_check as well, since we are now installing Python34 from EPEL and not our own repo.

2017-04-26 15:51 UTC, rioh commented on deploy/roles/python3/tasks/main.yml
>      disable_gpg_check: yes
@tanderegg Done!

2017-04-26 17:00 UTC, tanderegg approved these changes

2017-04-26 17:00 UTC, merged