Allow admins to read EOD logs
cfpb/aurora pull request #215
Opened 2017-05-11 20:01 UTC by stirlingv

@tanderegg This will fail the travis build, since it doesn't include all the regression changes included in the travis_timeout branch. It will also likely have merge conflicts in the travis.yml file and the deploy_research_environment.yml (the changes in this are to remove what looks like a typo) files. I should be able to resolve those easily once the travis_timeout branch is merged in.

2017-05-22 19:01 UTC, tanderegg requested changes

2017-05-22 19:01 UTC, tanderegg commented on deploy/roles/eod/tasks/main.yaml
> +
@stirlingv Isn't this group already created in the `common` role?

2017-05-22 19:01 UTC, tanderegg commented on deploy/roles/eod/tasks/main.yaml
> +    state: present
@stirlingv Don't we need to sections here, one with `default: yes` and the other `recursive: yes`?

2017-05-23 14:41 UTC, stirlingv commented on deploy/roles/eod/tasks/main.yaml
> +
It is, we don't call the common role in the research_eod host of the research deployment. 
```
- hosts: research_eod
  become: yes
  become_method: sudo
  roles:
    - eod
    - odbc
```

We can either add the common role to that host, or create the group name like I did here.

2017-05-23 14:44 UTC, tanderegg commented on deploy/roles/eod/tasks/main.yaml
> +
@stirlingv The common role is applied in the `hosts: research_environment` block at the top of the playbook, which applies to all servers in the RE, so you can safely remove this block, thanks!

2017-05-23 14:44 UTC, tanderegg commented on deploy/roles/eod/tasks/main.yaml
> +    state: present
@stirlingv I meant "two sections" not "to sections" :)

2017-05-24 20:37 UTC, stirlingv commented on deploy/roles/eod/tasks/main.yaml
> +    state: present
@tanderegg I am looking at this now - When I first did this there was a reason I didn't have a recursive parameter. I'll keep ya posted...

2017-06-01 13:43 UTC, tanderegg approved these changes

2017-06-01 13:43 UTC, merged