Update Data Warehouse to 9.6
cfpb/aurora pull request #258
Opened 2017-07-31 21:35 UTC by tanderegg

2017-07-31 21:36 UTC, tanderegg commented
@rioh @stirlingv Could you take a look when you have a chance?  Thanks!

2017-08-01 14:11 UTC, stirlingv reviewed
Looks good, small comment about a single typo - Travis helped catch!

2017-08-01 14:11 UTC, stirlingv commented on deploy/roles/postgresql-server/tasks/main.yml
> +    tags:
remove space before tags:

2017-08-07 13:04 UTC, rioh requested changes
Seems to be a typo on line 78

2017-08-10 16:27 UTC, tanderegg commented
@rioh Woops, thanks!

2017-08-10 16:27 UTC, merged