Pg10 upgrade
cfpb/aurora pull request #336
Opened 2018-02-13 14:51 UTC by rioh

2018-02-23 18:24 UTC, tanderegg requested changes

2018-02-23 18:24 UTC, tanderegg commented on deploy/roles/postgresql-server/vars/edb.yml
>  pp_download_url: "http://get.enterprisedb.com/ga/edb-as96-meta-9.6.2.7-2-linux-x64.tar.gz"
@rioh Should these two be updated to 10.x as well?

2018-02-23 18:24 UTC, tanderegg commented on deploy/roles/postgresql-server/vars/edb.yml
>  pp_old_bindir: /opt/PostgresPlus/9.4AS/bin
@rioh Also here, > 10.0 and 9.6 respectively

2018-02-23 18:24 UTC, tanderegg commented on deploy/roles/python-libs/defaults/main.yml
> +python3_pip_bin: /usr/local/bin/pip3.4
I think now that we are using the EPEL version of python3, it should be /usr/bin/ not /usr/local/bin, right?

2018-02-23 18:24 UTC, tanderegg commented on deploy/upgrade_db_server.yml
>    become_method: sudo
@rioh Add `serial: 1` and `max_failure_percentage: 1%` as described here: http://docs.ansible.com/ansible/latest/playbooks_delegation.html#rolling-update-batch-size, and here: http://docs.ansible.com/ansible/latest/playbooks_delegation.html#maximum-failure-percentage, to ensure failure of any one host will stop the process.

2018-02-26 19:59 UTC, rioh commented on deploy/roles/python-libs/defaults/main.yml
> +python3_pip_bin: /usr/local/bin/pip3.4
I'll take this out - wasn't supposed to be checked in.

2018-02-27 21:05 UTC, tanderegg approved these changes

2018-02-27 21:08 UTC, tanderegg requested changes
One last change

2018-02-27 21:08 UTC, tanderegg commented on deploy/upgrade_db_server.yml
>    become_method: sudo
@rioh Can you add the serial part here too?  This role will restart the server(s), so we should do that in order rather than parallel..

2018-02-27 22:05 UTC, merged